### ISSUE TITLE
Custom Domains Error

### ISSUE THREAD

**Issue by AcedDown** [sylveon/discord-ban-appeals#21]
In the sign in process, an error shows up saying "Invalid URI", I know, The URI needs to be set as the website url thing, but how do i edit that on github?

**Comment by sylveon** [comment]
Open the application you are using for the appeals site in the Discord Developer Portal, then open the OAuth2 section.

Click on Add Redirect and enter `https://mysite.com/.netlify/functions/oauth-callback` (replacing `mysite.com` with the appropriate domain, of course)

**Comment by Aceeeeeeeeeee** [comment]
I already did that before posting.
When I add a redirect uri for the new domain on Add Redirect,
When i enter the website and click on appeal, it just redirects me to the uri of the project's netlify domain, not the custom one

**Comment by sylveon** [comment]
You need to redeploy the site for domain changes to fully propagate. In the Netlify dashboard, click Deploys, and then Trigger deploy. In the menu that shows up, hit Deploy site.
