### ISSUE TITLE
Invaild OAuth2 redirect_uri

### ISSUE THREAD

**Issue by masterofninja** [sylveon/discord-ban-appeals#22]
i did the steps but it keep showing this

**Comment by masterofninja** [comment]
Invaild OAuth2 redirect_uri

**Comment by sylveon** [comment]
Open the application you are using for the appeals site in the Discord Developer Portal, then open the OAuth2 section.

Click on Add Redirect and enter `https://mysite.netlify.app/.netlify/functions/oauth-callback` (replacing `mysite` with the appropriate name, of course)

**Comment by Jansiman** [comment]
Sadly...I'm having the same issue, even while after adding a redirect with the "mysite" replaced my actual name for the site...

**Comment by kyle95wm** [comment]
A friend of mine is also having this issue. I checked and they added the callback URL

**Comment by Whanos** [comment]
I just set it up, and it works fine. Can you attach a photo of your website URL and your callback URL. For a working example I have attached mine
https://i.imgur.com/U94Z8xQ.png (OAuth URL)
Appeals site is "banappeals.sergal.fun"

**Comment by kyle95wm** [comment]
I forgot I commented here. The issue fixed itself

**Comment by Whanos** [comment]
Please close the issue then @kyle95wm .

**Comment by kyle95wm** [comment]
> Please close the issue then @kyle95wm .

Wrong person. I was simply contributing to this issue. You'll need to ping OP and get them to close it if they fixed the issue.

**Comment by Whanos** [comment]
Ah. My apologies. @masterofninja If it's alright now please close the issue

**Comment by sylveon** [comment]
Closing because OP never replied
