### ISSUE TITLE
I'm getting this error 

### ISSUE THREAD

**Issue by MisplaceDatabase** [sylveon/discord-ban-appeals#27]
I'm getting this error 

{"errorType":"Error","errorMessage":"Failed to get user ban","trace":["Error: Failed to get user ban","    at getBan (/var/task/src/func/helpers/user-helpers.js:41:15)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async Runtime.exports.handler (/var/task/src/func/oauth-callback.js:35:25)"]}

**Comment by MisplaceDatabase** [comment]
Also, the bot is not coming online too

**Comment by sylveon** [comment]
Bot will never come online, that's expected.
The failed to get user ban error is because you didn't give it the ban permissions:
![image](https://user-images.githubusercontent.com/6440374/120856934-88500a80-c54e-11eb-8b5f-7ad2d46ed18a.png)
