### ISSUE TITLE
Bypass Ban Checking

### ISSUE THREAD

**Issue by certifiedkatgirl** [sylveon/discord-ban-appeals#31]
Hey, so I customized my form but I don't know javascript. How do I make it bypass the ban checking and just let me go to the form like the example you put on this repo's description because I'm getting a 404 error, might be because I deleted the error.html file since I don't need it.

**Comment by sylveon** [comment]
Create an environment variable named `SKIP_BAN_CHECK` in the Netlify dashboard and set its value to `true`

**Comment by certifiedkatgirl** [comment]
> Create an environment variable named `SKIP_BAN_CHECK` in the Netlify dashboard and set its value to `true`

Thank you very much for responding fast!

**Comment by certifiedkatgirl** [comment]
Oh, I still getting an error. It redirects me to https://report.nativelighting.xyz/error?code=OxsXkdihKAaLCjrlqiDYX92rn497Dc&state=%5BA%23RhI%7B%26TJpOG%40P%21%25tc%5BdH%22rw%5E9
when I click the button

**Comment by certifiedkatgirl** [comment]
Nevermind, I was required to have a error.html so everything will continue working. It's all fixed. This is so useful thank u so much!
