### ISSUE TITLE
Selfhosting

### ISSUE THREAD

**Issue by ghost** [sylveon/discord-ban-appeals#34]
Hi, I was wondering if there was a way to selfhost this rather than on netlify?

**Comment by sylveon** [comment]
The code in `public` is just plain HTML, easily selfhostable. The code in `func` is a bit harder, as it's AWS lambda code. You can upload those as lambdas on AWS, they should work (you'll need to run [`netlify build`](https://docs.netlify.com/cli/get-started/#run-builds-locally) to obtain the final files).

If you desire everything on a single server without reliance on AWS, then you can use [lambda-local](https://github.com/ashiina/lambda-local) to run them locally.

Might have to update the HTML files to change where it points to for the function calls, as right now it uses `/.func/<function-name>`, which is Netlify-specific.

Hope that helps! Feel free to ask if you encounter any issue.

**Comment by mjkzy** [comment]
i basically just did some tinkering and got rid of the AWS lambdas and used express.js to host. with lots of messing around, I recreated it to work and it's pretty nice :D

**Comment by Shayshon** [comment]
> i basically just did some tinkering and got rid of the AWS lambdas and used node's express.js to host. with lots of messing around, I recreated it to work and it's pretty nice :D

I'll try that and see how it goes

**Comment by mjkzy** [comment]
> I'll try that and see how it goes
its not recommended due to the fact you need to get rid of the lambdas and build it all into the app.js, which is where the web server stuff for express.js takes place. i may open source my code soon and you can use it if you like then.
