### ISSUE TITLE
help

### ISSUE THREAD

**Issue by louisplayzz** [sylveon/discord-ban-appeals#43]
{"errorType":"Error","errorMessage":"Failed to get user ban","trace":["Error: Failed to get user ban","    at getBan (/var/task/func/helpers/user-helpers.js:41:15)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.exports.handler (/var/task/func/oauth-callback.js:44:25)"]}

**Comment by sylveon** [comment]
Did you grant the bot permission to manage bans?

**Comment by louisplayzz** [comment]
yes

Op wo 29 dec. 2021 om 01:32 schreef Charles Milette <
***@***.***>:

**Comment by louisplayzz** [comment]
yea

**Comment by louisplayzz** [comment]
i forgot that XD 

now its working
