### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ghost** [sylveon/discord-ban-appeals#45]
Not working

**Comment by sylveon** [comment]
Could you be more descriptive? How isn't it working?

**Comment by allaboutishaan** [comment]
{"errorType":"Error","errorMessage":"Failed to get user ban","trace":["Error: Failed to get user ban","    at getBan (/var/task/func/helpers/user-helpers.js:41:15)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.exports.handler (/var/task/func/oauth-callback.js:44:25)"]}

**Comment by jcsumlin** [comment]
It failed to fetch a users ban status [here](https://github.com/sylveon/discord-ban-appeals/blob/master/func/helpers/user-helpers.js#L33) which means one of the three variables could be wrong. I would first try triggering a deploy to make sure environment variables are set properly then maybe checking the bot's permissions

**Comment by allaboutishaan** [comment]
Thank you so much, I was able to fix it. I really appreciate it!
