### ISSUE TITLE
Bot error 

### ISSUE THREAD

**Issue by AMF-Academie-Militaire-Francaise** [sylveon/discord-ban-appeals#48]
{"errorType":"Error","errorMessage":"Dynamic require of \"buffer\" is not supported","trace":["Error: Dynamic require of \"buffer\" is not supported","    at __require (file:///var/task/func/oauth-callback.js:11:9)","    at node_modules/safe-buffer/index.js (file:///var/task/func/oauth-callback.js:4404:18)","    at __require2 (file:///var/task/func/oauth-callback.js:17:44)","    at node_modules/jws/lib/sign-stream.js (file:///var/task/func/oauth-callback.js:4935:19)","    at __require2 (file:///var/task/func/oauth-callback.js:17:44)","    at node_modules/jws/index.js (file:///var/task/func/oauth-callback.js:5115:22)","    at __require2 (file:///var/task/func/oauth-callback.js:17:44)","    at node_modules/jsonwebtoken/decode.js (file:///var/task/func/oauth-callback.js:5148:15)","    at __require2 (file:///var/task/func/oauth-callback.js:17:44)","    at node_modules/jsonwebtoken/index.js (file:///var/task/func/oauth-callback.js:7205:15)"]}

**Comment by sylveon** [comment]
I'm not seeing that issue on the current preview page, which ships the content of the current master branch. Do you have a page which reproduces the issue? Did you make any changes to it?

**Comment by sylveon** [comment]
Are you using netlify?

**Comment by AMF-Academie-Militaire-Francaise** [comment]
Yes,

**Comment by sylveon** [comment]
I just did a fresh deploy of the current preview and everything works. Are you on the latest commit of the project?

**Comment by AMF-Academie-Militaire-Francaise** [comment]
I will try new ones
