### ISSUE TITLE
site is unsafe

### ISSUE THREAD

**Issue by IlyasMooerkens** [sylveon/discord-ban-appeals#50]
if i try to connect my discord on the site it says website is unsafe it there a way that you can not see that anymore

**Comment by IlyasMooerkens** [comment]
https://i.imgur.com/KR1bkGy.png

**Comment by sylveon** [comment]
This is Chrome flagging the .tk TLD because it is free and therefore often used to host malware. If you purchase something like a .com/.net domain, or use the Netlify-provided netlify.app subdomain, Chrome shouldn't flag it anymore.
