### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by zimo-gu** [sylveon/discord-ban-appeals#54]
Thats what I get when I test it out.

**Comment by sylveon** [comment]
DId you set the redirect URI correctly on the developer dashboard?

> Go back to the [Discord Developer Portal](https://discord.com/developers/applications), open the dashboard for the application you created in step 1, and click on OAuth2.
> Click on Add Redirect and enter `https://[site-name].netlify.app/.netlify/functions/oauth-callback`, replacing `[site-name]` by the name you picked in step 8 (or the entire Netlify domain by your own domain, if you opted for that).

**Comment by NightFallCP** [comment]
still doesn't work for me
