### ISSUE TITLE
Why does it say invalid Oauth?

### ISSUE THREAD

**Issue by Depthify** [sylveon/discord-ban-appeals#56]
I had put https://ban-appeal-dt.netlify.app/api/oauth-callback.
![opera_DitJpp33zx](https://user-images.githubusercontent.com/107516153/175769387-90b26d09-0bde-4a25-9bc8-a00443b849c9.png)

**Comment by justin321123** [comment]
How did you fix this?

**Comment by Depthify** [comment]
wait, how did you find my email??

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 22, 2022 at 1:51, ***@***.***> wrote:   


How did you fix this?

**Comment by sylveon** [comment]
This is a GitHub issue notification, not a direct email
