### ISSUE TITLE
Show Who Unbanned or Remove Unban Button

### ISSUE THREAD

**Issue by reverb5264** [sylveon/discord-ban-appeals#69]
One of our mods unbanned someone and the audit log is only showing the bot unbanned them, therefore not allowing us to trace who actually unbanned them. I’d either like a way to trace who hit the button or a way to remove the button entirely and have mods manually unban instead.

**Comment by sylveon** [comment]
You can set the environment variable DISABLE_UNBAN_LINK to 1 to remove the ban button

**Comment by sylveon** [comment]
Related: #70
