### ISSUE TITLE
Form no longer working despite no recent changes made

### ISSUE THREAD

**Issue by reverb5264** [sylveon/discord-ban-appeals#71]
Received following error after submitting appeal on banned account

<img width="864" alt="Screenshot 2023-04-22 at 7 34 11 PM" src="https://user-images.githubusercontent.com/35243702/233816394-cf2c75c0-3fb5-4bd6-b85b-b8a8b25531e2.png">

**Comment by sylveon** [comment]
Did you delete the webhook? You can also check the logs in netlify's console to see what error discord returned.
