### ISSUE TITLE
invalid oauth2 redirect_uri

### ISSUE THREAD

**Issue by Dinspit** [sylveon/discord-ban-appeals#74]
I have error when try to login with discord on site

![image](https://github.com/sylveon/discord-ban-appeals/assets/91454173/8110ec33-13b8-4af5-88c8-b060287c3744)

![image](https://github.com/sylveon/discord-ban-appeals/assets/91454173/a537a77e-724a-40f3-85b0-0725a0ea7690)
![image](https://github.com/sylveon/discord-ban-appeals/assets/91454173/c3b8dfc4-c1fb-4cca-a628-1eadb82140e3)

**Comment by sylveon** [comment]
What's the redirect URI in the URL of the page giving this error? Also, try redeploying.

**Comment by Dinspit** [comment]
Im fixed it.
