### ISSUE TITLE
site function has crashed 

### ISSUE THREAD

**Issue by Dinspit** [sylveon/discord-ban-appeals#76]
I can't fix this error it disappeared a couple of times and everything worked stably but now it doesn't work at all.

![image](https://github.com/sylveon/discord-ban-appeals/assets/91454173/a103a49e-48b3-46a0-a1f2-6d9318913f17)
![image](https://github.com/sylveon/discord-ban-appeals/assets/91454173/76fe00cb-68c2-4fca-a2e9-7faa365c256f)

Full error log message:
Jul 4, 01:43:53 PM: a3a04e05 Duration: 392.45 ms	Memory Usage: 66 MB	Init Duration: 231.80 ms	Jul 4, 02:36:09 PM: cf08ffe5 INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:36:09 PM: cf08ffe5 ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:36:09 PM: cf08ffe5 Duration: 268.32 ms	Memory Usage: 67 MB	Init Duration: 242.57 ms	Jul 4, 02:36:35 PM: 697ce585 INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:36:35 PM: 697ce585 ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:36:35 PM: 697ce585 Duration: 245.72 ms	Memory Usage: 67 MB	Jul 4, 02:37:14 PM: 5b154b6e INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:37:14 PM: 5b154b6e ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:37:14 PM: 5b154b6e Duration: 230.69 ms	Memory Usage: 69 MB	Jul 4, 02:37:58 PM: a68f93ef INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:37:58 PM: a68f93ef ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:37:58 PM: a68f93ef Duration: 279.24 ms	Memory Usage: 69 MB	Jul 4, 02:47:45 PM: 557a0e8a INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:47:45 PM: 557a0e8a ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:47:46 PM: 557a0e8a Duration: 325.35 ms	Memory Usage: 66 MB	Init Duration: 250.41 ms	Jul 4, 02:48:28 PM: 95d264c1 INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:48:28 PM: 95d264c1 ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:48:29 PM: 95d264c1 Duration: 254.18 ms	Memory Usage: 67 MB	Jul 4, 02:50:37 PM: 09bd6e78 INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:50:37 PM: 09bd6e78 ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:50:37 PM: 09bd6e78 Duration: 254.40 ms	Memory Usage: 69 MB	Jul 4, 02:55:20 PM: f9c53254 INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:55:20 PM: f9c53254 ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:55:21 PM: f9c53254 Duration: 229.85 ms	Memory Usage: 69 MB	Jul 4, 02:56:06 PM: 2ae609fc INFO   { message: '401: Unauthorized', code: 0 }Jul 4, 02:56:06 PM: 2ae609fc ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"Failed to get user ban","stack":["Error: Failed to get user ban","    at getBan (/var/task/func/oauth-callback.js:14923:11)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async Runtime.handler (/var/task/func/oauth-callback.js:14998:21)"]}Jul 4, 02:56:06 PM: 2ae609fc Duration: 212.02 ms	Memory Usage: 69 MB

**Comment by sylveon** [comment]
Looks like you were missing the ban permission, for future reference
